version: 0.2


env:
  parameter-store:
    WELCOME: "welcome"

phases:
  build:
    commands:
      - echo $WELCOME
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python helloworld.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - helloworld.py
