version: 0.2


env:
  parameter-store:
    hello: "welcome"

phases:
  install:
    commands:
      - pip install awscli

  build:
    commands:
      - pip list
      - echo ${hello}
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python helloworld.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - helloworld.py
